### ISSUE TITLE
Feature request: add OnTransition callback to Transition class

### ISSUE THREAD

**Issue by rafaeldolfe** [Inspiaaa/UnityHFSM#24]
Add OnTransition event to the Transition class, so that when you add a transition, and that transition happens, a specific function can be called. 

Otherwise you have to do things like setting the function in OnEnter/OnExit and then check for the state or store separately which transition is being used. Not very easy to use.

**Comment by Monsoonexe** [comment]
I like this idea. You can run logic on specific state transitions.

**Comment by Monsoonexe** [comment]
Looks all you need to do is override ShouldTransition(), and if you would
return true, then raise the event.

**Comment by Inspiaaa** [comment]
Hi @rafaeldolfe,
Your idea for this new feature is really good! I'm going to implement this feature in the next release (1.10). I'm already working on 1.10 and you can see the changes in the `release` branch. If you monitor the release 1.10 branch, you'll soon see that I'm taking a different approach from @Monsoonexe's proposal. My reason for a different approach is based on the timing system so that the on transition action can also be called when a transition is delayed (pending state system).
As to @rafaeldolfe's last comment, the answer is yes. It will work with all transition types.

**Comment by rafaeldolfe** [comment]
Sounds awesome! Will be watching 👌

**Comment by tomsseisums** [comment]
This is already available in yet unreleased, but available 2.0 version. :)

**Comment by bvggeneral** [comment]
@Inspiaaa 
I believe this is done with 2.0, right? 🎉 
I'd be down to close this issue.

**Comment by rafaeldolfe** [comment]
(Comment above is me)
I'll close this!
