### ISSUE TITLE
Are there reasons to not use this library outside of Unity?

### ISSUE THREAD

**Issue by Zergleb** [Inspiaaa/UnityHFSM#42]
Are there any hard dependencies on Unity?

**Comment by Inspiaaa** [comment]
Hi @Zergleb,

Although UnityHFSM has some features that are specifically designed for Unity, **the core of the library is universal** and can be used in any environment. I have made an effort to minimise its reliance on the tools and features provided by Unity.

This means that you can make a few changes to the source code in order to use it outside of Unity. The main disadvantage is that some features (e.g. support for coroutines) will be unavailable, unless you implement them yourself for the engine or framework that you are working with.

For a step-by-step guide on how you can do this, check out the [wiki](https://github.com/Inspiaaa/UnityHFSM/wiki/Using-UnityHFSM-outside-of-Unity).
